idci_payment:
    templates:
        step:
            approved: '@IDCIPaymentBundle/Resources/views/PaymentStep/approved.html.twig'
            canceled: '@IDCIPaymentBundle/Resources/views/PaymentStep/canceled.html.twig'
            created: '@IDCIPaymentBundle/Resources/views/PaymentStep/created.html.twig'
            failed: '@IDCIPaymentBundle/Resources/views/PaymentStep/failed.html.twig'
            pending: '@IDCIPaymentBundle/Resources/views/PaymentStep/pending.html.twig'
